kind: pipeline
name: example-drone
type: docker

steps:
  - name: test and code coverage
    image: python
    commands:
      - sleep 5
      - pip install -r requirements.txt
      - python app.py
 
services:
- name: redis
  image: redis
  volumes:
    - name: redisdb
      path: /data
volumes:
  - name: redisdb
    host:
      path: /tmp/drone/drone-example/rdb
